# -*- coding: utf-8 -*-
"""
Language database for RepoPrep.

For each language we track three things:
  - how to recognise it (manifest / config file names at the project root)
  - the folders that are pure junk for that language (dependencies,
    caches, build output)
  - the files that are junk (lock files, generated artifacts)

The list is broad on purpose. Patterns may use `*` globs (e.g. "*.csproj");
exact names are matched as-is. Junk names are kept conservative — nothing
that could be genuine source code ever goes in here.
"""

# (name, manifest patterns, junk dirs, junk files)
LANGUAGES = (
    # ── Python ──────────────────────────────────────────────────────────
    ("Python", ("requirements.txt", "setup.py", "setup.cfg", "pyproject.toml",
                "Pipfile", "tox.ini", "manage.py", "environment.yml"),
     ("__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".tox",
      ".nox", ".eggs", ".uv", ".direnv", "site-packages", "dist-packages",
      "htmlcov", ".hypothesis", "*.egg-info"),
     ("poetry.lock", "Pipfile.lock", "uv.lock", ".coverage")),
    ("Django", ("manage.py", "django.ini", "settings.py"),
     ("staticfiles", "media", "logs"), ()),
    ("Cython", ("*.pyx", "*.pxd"),
     ("build",), ("*.so",)),
    # ── JavaScript ecosystem ────────────────────────────────────────────
    ("JavaScript", ("package.json", ".nvmrc", ".node-version", "jsconfig.json",
                    "nodemon.json", "gulpfile.js", "gruntfile.js"),
     ("node_modules", ".npm", ".yarn", ".pnpm-store", ".cache", ".parcel-cache",
      ".webpack", ".turbo", ".vite", "coverage"),
     ("package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb",
      "bun.lock", ".yarn-integrity")),
    ("TypeScript", ("tsconfig.json", "tsconfig.app.json", "tsconfig.node.json"),
     ("node_modules", ".cache", ".turbo", "coverage"), ("*.tsbuildinfo",)),
    ("CoffeeScript", ("*.coffee", "*.litcoffee"), ("node_modules",), ()),
    ("React", ("jsconfig.json", "vite.config.js", "vite.config.ts",
               "craco.config.js"),
     ("node_modules", ".vite", "coverage"), ()),
    ("Next.js", ("next.config.js", "next.config.mjs", "next.config.ts"),
     ("node_modules", ".next", ".vercel", ".output"), ()),
    ("Nuxt", ("nuxt.config.js", "nuxt.config.ts", "nuxt.config.mjs"),
     ("node_modules", ".nuxt", ".output"), ()),
    ("Vue", ("vue.config.js", "*.vue"), ("node_modules", "dist"), ()),
    ("Svelte", ("svelte.config.js", "*.svelte"), ("node_modules", ".svelte-kit"), ()),
    ("Angular", ("angular.json", "*.component.ts"),
     ("node_modules", ".angular", "coverage"), ()),
    ("Ember", ("ember-cli-build.js",), ("node_modules", "dist", ".ember"), ()),
    ("Gatsby", ("gatsby-config.js", "gatsby-config.ts"),
     ("node_modules", ".cache", "public"), ()),
    ("React Native", ("app.json", "app.config.js", "metro.config.js"),
     ("node_modules", "android/app/build", "ios/Pods", "ios/build",
      ".expo", ".metro"), ()),
    ("Docusaurus", ("docusaurus.config.js", "docusaurus.config.ts"),
     ("node_modules", "build", ".docusaurus"), ()),
    ("Deno", ("deno.json", "deno.jsonc", "import_map.json"), ("node_modules",), ("deno.lock",)),
    ("Bun", ("bunfig.toml",), ("node_modules",), ("bun.lockb", "bun.lock")),
    ("Electron", ("electron-builder.yml", "electron-builder.json",
                  "electron.vite.config.ts"),
     ("node_modules", "out", "dist-electron", "release"), ()),
    # ── Web / styling / templates ───────────────────────────────────────
    ("HTML", ("*.html", "*.htm", "index.html"), (), ()),
    ("CSS", ("*.css", "*.map.css"), (), ()),
    ("Sass/SCSS", ("*.scss", "*.sass", "*.sassmap"), ("node_modules",), ()),
    ("Less", ("*.less",), ("node_modules",), ()),
    ("Stylus", ("*.styl", "*.stylus"), ("node_modules",), ()),
    ("PostCSS", ("postcss.config.js", "postcss.config.cjs"), ("node_modules",), ()),
    ("Tailwind CSS", ("tailwind.config.js", "tailwind.config.ts", "tailwind.config.cjs"),
     ("node_modules", ".cache"), ()),
    ("Jinja2", ("*.jinja", "*.jinja2", "templates/base.html"), (), ()),
    ("Handlebars", ("*.hbs", "*.handlebars"), ("node_modules",), ()),
    ("Pug", ("*.pug", "*.jade"), ("node_modules",), ()),
    ("Markdown", ("*.md", "*.mdx", "README.md"), (), ()),
    ("reStructuredText", ("*.rst", "*.rest"), ("_build",), ()),
    ("AsciiDoc", ("*.adoc", "*.asciidoc"), (), ()),
    ("Org Mode", ("*.org",), (), ()),
    ("LaTeX", ("*.tex", "*.sty", "*.cls"), (),
     ("*.aux", "*.toc", "*.lof", "*.lot", "*.out", "*.synctex.gz", "*.fls",
      "*.fdb_latexmk", "*.blg", "*.bbl", "_minted-*")),
    ("SVG", ("*.svg",), (), ()),
    ("JSON", ("*.json",), (), ()),
    ("YAML", ("*.yaml", "*.yml"), (), ()),
    ("TOML", ("*.toml",), (), ()),
    ("XML", ("*.xml", "*.xsd", "*.xsl"), (), ()),
    ("GraphQL", ("*.graphql", "*.gql", "schema.graphql", "queries/*.graphql"), (), ()),
    # ── Data / config / infra languages ──────────────────────────────────
    ("SQL", ("*.sql", "*.ddl", "*.dml"), (), ()),
    ("PL/SQL", ("*.pls", "*.plsql", "*.pks", "*.pkb"), (), ()),
    ("T-SQL", ("*.tsql",), (), ()),
    ("PostgreSQL", ("*.pgsql",), (), ()),
    ("Protobuf", ("*.proto",), (), ()),
    ("Thrift", ("*.thrift",), (), ()),
    ("FlatBuffers", ("*.fbs",), (), ()),
    ("OpenAPI", ("openapi.yaml", "openapi.yml", "swagger.json", "swagger.yaml"),
     (), ()),
    ("Docker/Compose", ("Dockerfile", "docker-compose.yml", "docker-compose.yaml",
                        "compose.yaml", "compose.yml", ".dockerignore"), (), ()),
    ("Kubernetes/Helm", ("Chart.yaml", "values.yaml", "kustomization.yaml",
                         "deployment.yaml", "service.yaml"), ("charts",), ()),
    ("Terraform/HCL", ("*.tf", "*.tfvars"), (".terraform",), ("*.tfstate",)),
    ("Ansible", ("ansible.cfg", "playbook.yml", "install.yml"), (".ansible",), ()),
    ("Packer", ("*.pkr.hcl",), (), ()),
    ("Vagrant", ("Vagrantfile",), (".vagrant",), ()),
    ("Nix", ("default.nix", "shell.nix", "flake.nix"), ("result",), ("flake.lock",)),
    ("PromQL", ("*.promql", "*.rules"), (), ()),
    # ── Shell / scripting ───────────────────────────────────────────────
    ("Bash/Shell", ("*.sh", "*.bash", ".bashrc", ".bash_profile"), (), ()),
    ("Zsh", ("*.zsh", ".zshrc"), (), ()),
    ("Fish", ("*.fish", "fishfile"), (), ()),
    ("PowerShell", ("*.ps1", "*.psd1", "*.psm1"), (), ()),
    ("Batch/CMD", ("*.bat", "*.cmd"), (), ()),
    ("VBScript", ("*.vbs",), (), ()),
    ("AppleScript", ("*.applescript", "*.scpt"), (), ()),
    ("AutoHotkey", ("*.ahk", "*.ah2"), ("bin",), ()),
    ("AutoIt", ("*.au3",), ("bin",), ()),
    ("AWK", ("*.awk",), (), ()),
    ("Sed", ("*.sed",), (), ()),
    ("Tcl/Tk", ("*.tcl", "*.tk"), (), ()),
    ("Expect", ("*.exp",), (), ()),
    # ── C-family ────────────────────────────────────────────────────────
    ("C", ("Makefile", "GNUmakefile", "configure.ac", "Kconfig", "*.c"),
     ("CMakeFiles", "cmake-build-debug", "cmake-build-release", ".deps"),
     ("CMakeCache.txt", "cmake_install.cmake", "Makefile.in", "config.log")),
    ("C++", ("CMakeLists.txt", "meson.build", "SConscript", "*.cc", "*.cpp",
             "*.hpp", "*.hxx"),
     ("CMakeFiles", "meson-private", "meson-logs", "cmake-build-debug",
      "cmake-build-release", ".cache", ".clangd"),
     ("CMakeCache.txt", "cmake_install.cmake", "compile_commands.json",
      "compile_flags.txt", ".ninja_deps", ".ninja_log")),
    ("Objective-C", ("*.m", "*.mm", "Podfile", "Cartfile"),
     ("Pods", "DerivedData", "build"), ("Podfile.lock", "Cartfile.resolved")),
    ("Swift", ("Package.swift", "*.swift"),
     (".build", "DerivedData", "build"), ("Package.resolved",)),
    ("C#", ("*.csproj", "*.sln", "*.cs", "global.json"),
     ("bin", "obj", ".vs", "TestResults", "packages"), ("*.user", "*.suo")),
    ("F#", ("*.fsproj", "*.fs", "*.fsx"), ("bin", "obj"), ()),
    ("VB.NET", ("*.vbproj", "*.vb"), ("bin", "obj"), ()),
    ("CUDA", ("*.cu", "*.cuh"), ("build",), ()),
    ("OpenCL", ("*.cl", "*.clh"), (), ()),
    ("Assembly", ("*.asm", "*.s", "*.S"), ("build", "obj"), ()),
    ("WebAssembly", ("*.wat", "*.wast"), (), ()),
    # ── JVM family ──────────────────────────────────────────────────────
    ("Java (Maven)", ("pom.xml", "mvnw", "*.java"),
     ("target", "node_modules"), ("*.iml",)),
    ("Java (Gradle)", ("build.gradle", "settings.gradle", "gradlew",
                       "build.gradle.kts"),
     (".gradle", "build", "app/build", "lib/build"), ("*.iml",)),
    ("Kotlin", ("*.kt", "*.kts"), (".kotlin", "build"), ()),
    ("Groovy", ("*.groovy", "*.gvy"), ("build",), ()),
    ("Scala", ("build.sbt", "*.scala", "*.sc"),
     (".scala-build", ".metals", ".bsp", ".bloop", "target"), ()),
    ("Clojure", ("project.clj", "deps.edn", "shadow-cljs.edn", "*.clj"),
     (".cpcache", ".clj-kondo", ".shadow-cljs", ".lsp", "out", "target"), ()),
    ("Gradle", ("*.gradle", "*.gradle.kts"), (".gradle",), ()),
    # ── Functional / other compiled langs ───────────────────────────────
    ("Rust", ("Cargo.toml", "*.rs"), ("target",), ("Cargo.lock",)),
    ("Go", ("go.mod", "Gopkg.toml", "go.work", "*.go"),
     ("vendor",), ("go.sum", "Gopkg.lock")),
    ("Dart/Flutter", ("pubspec.yaml", "*.dart"),
     (".dart_tool", ".flutter-plugins", ".flutter-plugins-dependencies", "build"),
     ("pubspec.lock", ".packages")),
    ("Kotlin/Compose", ("*.kt",), ("build", ".kotlin"), ()),
    ("Haskell", ("stack.yaml", "cabal.project", "*.cabal"),
     (".stack-work", "dist-newstyle"),
     ("stack.yaml.lock", "cabal.project.local", ".ghc.environment.*")),
    ("Elm", ("elm.json", "*.elm"), ("elm-stuff",), ()),
    ("PureScript", ("spago.yaml", "spago.dhall", "*.purs"),
     (".spago", "output"), ()),
    ("Erlang", ("rebar.config", "*.erl", "*.hrl"),
     ("_build",), ("rebar.lock",)),
    ("Elixir", ("mix.exs", "*.ex", "*.exs"),
     ("_build", "deps", ".elixir_ls", ".fetch"), ("mix.lock",)),
    ("Gleam", ("gleam.toml", "*.gleam"), ("build",), ("gleam.lock",)),
    ("OCaml", ("dune-project", "dune", "*.ml", "*.mli"),
     ("_build", ".merlin"), ()),
    ("Standard ML", ("*.sml", "*.sig"), ("_build",), ()),
    ("Nim", ("*.nimble", "nim.cfg", "*.nim"),
     ("nimcache", ".nimble", "build"), ()),
    ("Crystal", ("shard.yml", "*.cr"), ("lib", ".crystal"), ("shard.lock",)),
    ("Zig", ("build.zig", "*.zig"), (".zig-cache", "zig-out"), ()),
    ("V", ("v.mod", "*.v"), ("vmodules", "vexec", "build"), ()),
    ("Odin", ("*.odin", "odin.json", "ols.json"), (), ()),
    ("Hare", ("*.ha",), (), ()),
    ("Idris", ("*.idr", "*.lidr"), ("build",), ()),
    ("Agda", ("*.agda", "*.lagda.md"), (), ()),
    ("Coq", ("*.v", "*.coq"), ("build",), ()),
    ("Lean", ("lakefile.lean", "lean-toolchain", "*.lean"),
     (".lake",), ("lake-manifest.json",)),
    ("Isabelle", ("*.thy",), ("output",), ()),
    ("ATS", ("*.dats", "*.sats", "*.hats"), ("node_modules", "build"), ()),
    # ── Lisp / symbolic languages ───────────────────────────────────────
    ("Common Lisp", ("*.lisp", "*.lsp", "*.asd", "*.cl"), (), ("*.fasl",)),
    ("Scheme", ("*.scm", "*.ss"), (), ()),
    ("Racket", ("info.rkt", "*.rkt"), ("compiled", ".racket"), ()),
    ("Emacs Lisp", ("*.el", "init.el"), (), ("*.elc",)),
    ("ClojureScript", ("*.cljs", "*.cljc"), ("node_modules", ".shadow-cljs"), ()),
    ("Smalltalk", ("*.st", "*.gtk", "*.mcz"), ("pharo-local",), ()),
    ("Prolog", ("*.pl", "*.pro"), (), ()),
    # ── Numeric / scientific / data analysis ────────────────────────────
    ("R", ("DESCRIPTION", "*.Rproj", "*.r", "*.R"),
     ("renv/library", ".Rproj.user", ".Rcheck", "check"),
     ("renv.lock", ".Rhistory", ".RData")),
    ("Julia", ("Project.toml", "Manifest.toml", "*.jl"),
     ("build",), ("Manifest.toml",)),
    ("MATLAB", ("*.m", "*.mlx"), (), ()),
    ("Octave", ("*.m", "*.oct"), (), ()),
    ("Mathematica/Wolfram", ("*.nb", "*.wl", "*.wls"), (), ()),
    ("Stata", ("*.do", "*.ado"), (), ()),
    ("SAS", ("*.sas",), (), ()),
    ("SPSS", ("*.sps", ".sav"), (), ()),
    ("Stan", ("*.stan",), ("build",), ()),
    # ── Scripting langs ─────────────────────────────────────────────────
    ("Perl", ("cpanfile", "Makefile.PL", "*.pl"),
     ("blib", "_build", ".cpanm"), ()),
    ("Raku", ("META6.json", "*.raku", "*.p6", "*.rakumod"), (), ()),
    ("Ruby", ("Gemfile", "Rakefile", "*.gemspec", "*.rb"),
     (".bundle", "vendor/bundle", "coverage"), ("Gemfile.lock",)),
    ("Rails", ("config.ru", "Gemfile"), ("log", "tmp", "public/assets", "public/packs"), ()),
    ("PHP/Composer", ("composer.json", "*.php"), ("vendor",), ("composer.lock",)),
    ("Laravel", ("artisan", "bootstrap/app.php"),
     ("vendor", "storage/framework/cache", "storage/framework/views",
      "bootstrap/cache", "node_modules"),
     ("composer.lock",)),
    ("WordPress", ("wp-config.php", "style.css.orig"), (), ()),
    ("Drupal", ("core.services.yml", "drupal-*.info.yml"), ("sites/default/files",), ()),
    ("Lua", ("*.lua", "*.rockspec", "luacheckrc"), ("bin",), ()),
    ("Haxe", ("haxelib.json", "*.hx", "project.xml"),
     (".haxelib", "export"), ()),
    ("GDScript (Godot)", ("project.godot", "*.gd"),
     (".godot", "*.import"), ()),
    ("Unreal Engine (C++)", ("*.uproject", "*.uplugin"),
     ("Intermediate", "DerivedDataCache", "Binaries", "Saved"),
     ("*.sln",)),
    # ── Build systems ───────────────────────────────────────────────────
    ("Make", ("Makefile", "GNUmakefile", "makefile"), (), (".depend",)),
    ("CMake", ("CMakeLists.txt", "*.cmake"),
     ("CMakeFiles",), ("CMakeCache.txt", "cmake_install.cmake")),
    ("Meson", ("meson.build", "meson_options.txt"),
     ("meson-private", "meson-logs", "meson-dist"), ()),
    ("Ninja", ("build.ninja", "rules.ninja"), (), (".ninja_deps", ".ninja_log")),
    ("Bazel", ("WORKSPACE", "WORKSPACE.bazel", "MODULE.bazel", "BUILD", "*.bzl"),
     ("bazel-bin", "bazel-out", "bazel-testlogs"), ()),
    ("SCons", ("SConstruct", "SConscript"), (), (".sconsign.dblite",)),
    ("Autotools", ("configure.ac", "configure.in", "Makefile.am"),
     ("autom4te.cache", ".deps"), ("configure", "Makefile.in")),
    ("Ant", ("build.xml", "*.ant"), ("build",), ()),
    # ── Mobile / game engines ───────────────────────────────────────────
    ("Flutter (app)", ("pubspec.yaml", "analysis_options.yaml"),
     (".dart_tool", "build"), ("pubspec.lock",)),
    ("Cordova", ("config.xml", "cordova.android"),
     ("node_modules", "platforms", "plugins", "www"), ()),
    ("Unity", ("ProjectSettings/ProjectVersion.txt", "*.unity"),
     ("Library", "Temp", "obj", "Logs", "UserSettings"), ()),
    ("Godot (C#)", ("*.csproj", "project.godot"), (".godot", "bin", "obj"), ()),
    ("Processing", ("*.pde",), (), ()),
    ("OpenSCAD", ("*.scad", "*.scadlib"), (), (".scadcache",)),
    ("Q#", ("*.qs", "*.qsharp"), ("obj", "qsharp-out", "bin"), ()),
    ("QML", ("*.qml", "*.qrc"), ("build",), ()),
    # ── Blockchain / smart contracts ────────────────────────────────────
    ("Solidity", ("hardhat.config.ts", "hardhat.config.js", "foundry.toml",
                  "truffle-config.js", "*.sol"),
     ("artifacts", "cache", "typechain-types", "node_modules"), ("broadcast",)),
    ("Vyper", ("*.vy", "*.vyper"), (".cache",), ()),
    ("Move", ("Move.toml", "*.move"), ("build",), ()),
    ("Cairo", ("Scarb.toml", "*.cairo"), ("target",), ()),
    ("Leo", ("leo.toml", "*.leo"), ("build",), ()),
    # ── Misc / older languages ──────────────────────────────────────────
    ("Fortran", ("*.f", "*.f90", "*.f95", "*.f03", "*.f08"),
     ("build",), ("*.mod", "*.smod")),
    ("COBOL", ("*.cbl", "*.cob", "*.cpy"), ("bin",), ()),
    ("Ada", ("*.adb", "*.ads", "*.gpr"), ("obj", ".obj", "build"), ()),
    ("Pascal/Delphi", ("*.dpr", "*.pas", "*.pp", "*.lpr"),
     ("__history", "__recovery", "Win32", "Win64", "lib"), ()),
    ("D", ("dub.json", "dub.sdl", "source/app.d"), (".dub", "build"), ()),
    ("Eiffel", ("*.e", "*.ecf"), ("EIFGENs",), ()),
    ("Forth", ("*.fth", "*.4th", "*.forth"), (), ()),
    ("Factor", ("*.factor",), ("work",), ()),
    ("Io", ("*.io",), (), ()),
    ("Janet", ("*.janet", "project.janet"), (), ()),
    ("LiveScript", ("*.ls",), ("node_modules",), ()),
    ("MoonScript", ("*.moon",), (), ()),
    ("Red", ("*.red", "*.reds"), (), ()),
    ("Wren", ("*.wren", "*.wrenc"), (), ()),
    ("Pony", ("*.pony",), ("build",), ()),
    ("Futhark", ("*.fut",), ("build",), ()),
    ("REXX", ("*.rex", "*.rexx"), (), ()),
    ("PL/I", ("*.pli", "*.plinc"), (), ()),
    ("RPG", ("*.rpgle", "*.rpg", "*.dspf"), (), ()),
    ("ABAP", ("*.abap",), (), ()),
    ("Visual Basic 6", ("*.vbp", "*.frm", "*.bas", "*.cls"),
     ("win32",), ("*.frx",)),
    ("xBase/Clipper", ("*.dbf", "*.prg"), (), ()),
    # ── Shaders / low level / formal ────────────────────────────────────
    ("GLSL", ("*.glsl", "*.vert", "*.frag", "*.comp", "*.geom", "*.tesc",
              "*.tese", "*.rgen", "*.rchit", "*.rmiss", "*.rint", "*.rahit"),
     ("spv",), ()),
    ("HLSL", ("*.hlsl", "*.fx", "*.fxh", "*.hlsl", "*.hlsli"), (), ()),
    ("Metal Shading", ("*.metal",), (), ()),
    ("ShaderLab", ("*.shader", "*.shadergraph"), ("Library",), ()),
    ("LLVM IR", ("*.ll", "*.bc"), (), ()),
    ("Verilog", ("*.v", "*.vh", "*.svh"), ("sim",), ()),
    ("SystemVerilog", ("*.sv",), ("sim",), ()),
    ("VHDL", ("*.vhd", "*.vhdl"), ("sim",), ()),
    ("TLA+", ("*.tla",), (), ()),
    ("Alloy", ("*.als",), (), ()),
    ("APL", ("*.apl", "*.dyalog"), (), ()),
    ("J", ("*.ijs",), (), ()),
    ("Q", ("*.q",), (), ()),
    ("BQN", ("*.bqn",), (), ()),
    # ── Framework / library junk packs ──────────────────────────────────
    ("Astro", ("astro.config.mjs", "astro.config.ts", "astro.config.js"),
     ("dist", ".astro", "node_modules"), ()),
    ("SvelteKit", ("svelte.config.js", "svelte.config.ts"),
     (".svelte-kit", "node_modules"), ()),
    ("Remix", ("remix.config.js", "remix.config.ts"),
     (".cache", "node_modules"), ()),
    ("Expo", ("app.json", "app.config.js", "app.config.ts", "expo-env.d.ts"),
     ("node_modules", ".expo", "dist"), ()),
    ("Storybook", ("*.stories.ts", "*.stories.tsx", "*.stories.js",
                   "*.stories.jsx"),
     ("node_modules", "storybook-static"), ()),
    ("Cypress", ("cypress.config.js", "cypress.config.ts", "cypress.json"),
     ("node_modules", "cypress/videos", "cypress/screenshots"), ()),
    ("Playwright", ("playwright.config.ts", "playwright.config.js"),
     ("node_modules", "test-results", "playwright-report", "blob-report"), ()),
    ("Jest", ("jest.config.js", "jest.config.ts", "jest.setup.js",
              "jest.setup.ts"),
     ("node_modules", "coverage", ".jest-cache"), ()),
    ("Vitest", ("vitest.config.js", "vitest.config.ts"),
     ("node_modules", "coverage", ".vitest"), ()),
    ("Turborepo", ("turbo.json",), ("node_modules", ".turbo"), ()),
    ("Nx", ("nx.json", "project.json"), ("node_modules", ".nx", "tmp"), ()),
    ("Lerna", ("lerna.json",), ("node_modules",), ("lerna-debug.log",)),
    ("NestJS", ("nest-cli.json",), ("node_modules", "dist"), ()),
    ("Capacitor", ("capacitor.config.ts", "capacitor.config.json"),
     ("node_modules",), ()),
    ("Symfony", ("composer.json", "symfony.lock"),
     ("vendor", "var/cache", "var/log"), ()),
    ("CakePHP", ("config/app.php",), ("vendor", "node_modules"),
     ("composer.lock",)),
    ("Spring Boot", ("pom.xml", "build.gradle", "application.yml",
                     "application.yaml", "application.properties"),
     ("target", ".gradle", ".mvn"), ()),
    ("Android (Kotlin/Java)",
     ("AndroidManifest.xml", "build.gradle", "settings.gradle",
      "gradle.properties", "build.gradle.kts", "settings.gradle.kts"),
     ("build", ".gradle", "captures", ".externalNativeBuild", ".cxx"),
     ("local.properties", "keystore.jks")),
    ("Swift Package Manager", ("Package.swift",), (".build",), ()),
    ("Jupyter", ("*.ipynb",), (".ipynb_checkpoints",), ()),
    ("MLflow", ("mlflow.db",), ("mlruns", ".mlflow"), ()),
    ("W&B", ("*.wandb",), ("wandb",), ()),
    ("DVC", ("dvc.yaml",), (".dvc",), ("dvc.lock",)),
    ("Jekyll", ("_config.yml", "Gemfile"),
     ("_site", ".jekyll-cache", ".sass-cache"), ()),
    ("VitePress", ("vitepress.config.ts", "vitepress.config.js"),
     ("node_modules", ".vitepress/dist"), ()),
    ("Sphinx", ("conf.py",), ("_build",), ()),
    ("Robot Framework", ("*.robot",), (), ("*.output.xml",)),
    ("Phoenix", ("mix.exs",), ("_build", "deps", "cover"), ("mix.lock",)),
    ("LaTeX Build", ("main.tex",), ("_minted",),
     ("*.aux", "*.fls", "*.fdb_latexmk", "*.out", "*.synctex.gz", "*.run.xml",
      "*.bcf", "*.bbl", "*.blg", "*.toc", "*.lof", "*.lot")),
)

# name -> entry index for quick access
NAME_TO_LANG = {entry[0]: entry for entry in LANGUAGES}